Reduce the size of the MUXC PCH by 20% (#12054)
## Description

The current Microsoft.UI.Xaml.Controls.pch file for an x64chk is 2.2 GB.
This huge size adds considerably to the required amount of available
memory+pagefile during a build of MUXC. If the compiler is free to run
parallel builds across all logical processes, this can be a considerable
drain: 2.2 GB * 24 logical processors is 53 GB, just for the PCH! If not
enough memory+pagefile is available, the build can fail with these
errors:
```
error C1076: compiler limit: internal heap limit reached
error C1060: compiler is out of heap space
```

Do a few things to reduce the PCH size:
1. Remove the #include of `winrt\Windows.Devices.Geolocation.h`: This is
only used by the MapControl, which already directly includes it, so it
is just overhead in the PCH.
2. Remove #includes for `winrt\Microsoft.UI.Input.Experiment.h` and
`winrt\Windows.ApplicationModel.Activation.h`, both of which appear to
be unused.
3. **BIG WIN:** Move the #include of `winrt\Windows.UI.Xaml.Interop.h`
into SelectionModel.cpp, the only file which needs it. This change alone
removed 460 MB from the PCH.

**Results:** The PCH is down to 1.73 GB, a 21% reduction. Here's the
before and after size, along with the memory reserve required for the
compiler on a machine with 24 logical processors:

| State  | PCH Size (GB) | Compiler Reserve, 24 Processors (GB) |
|--------|--------------:|-------------------------------------:|
| Before |         2.210 |                               53.030 |
| After  |         1.728 |                               41.471 |

That is a huge reduction on compiler reserve, though obviously it would
be great to reduce it further. But it is a start and some testing didn't
find significant easy wins with further #include removals (all appear to
be used, and each is 20 MB or less impact per header).

Testing of build speed when limited to two cores found this also reduced
the total build time of MUXC by roughly 6% (322 seconds compared to 354
before), though that savings will undoubtedly be less when more
parallelization is allowed.

## PR Type

- [x] Build related changes

## How Has This Been Tested?

- [x] I have performed a self-review of my own code
- [x] Existing tests pass locally -- still builds!